set-option -g status-style bg=default,fg=default
set -g status off
bind-key -n F12 set-option -g status

set-option -g status-left ""
set-option -g status-right ""
set-window-option -g window-status-format "#I:#W"
set-window-option -g window-status-current-format "#I:#W"

set -g prefix C-f
bind -n C-Tab next-window
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R
