[ids]
*

[main]
capslock = overload(control, esc)
rightshift = backspace

[control]
h = left
j = down
k = up
; = right
u = pageup

[control+shift]
h = C-S-left
j = C-S-down
k = C-S-up
; = C-S-right

[control+alt]
h = C-left
j = C-down
k = C-up
; = C-right
